src/Entity/Record.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecordRepository")
 */
class Record
{
    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, options={"comment": "账户"})
     */
    private $account;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, options={"comment": "描述"})
     */
    private $description;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, options={"comment": "分类"})
     */
    private $category;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime", options={"comment": "日期时间"})
     */
    private $datetime;

    /**
     * @var float
     * @ORM\Column(type="float", options={"comment": "金额"})
     */
    private $amount;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, options={"comment": "货币"})
     */
    private $currency;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, options={"comment": "标签"})
     */
    private $tags;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getAccount(): string
    {
        return $this->account;
    }

    public function setAccount(string $account): self
    {
        $this->account = $account;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string
     */
    public function getCategory(): string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getDatetime(): \DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * @return float
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return string
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * @return string
     */
    public function getTags(): string
    {
        return $this->tags;
    }

    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getRecordedAt(): string
    {
        if ($this->getDatetime()) {
            return $this->getDatetime()->format('Y-m-d H:i');
        }

        return '';
    }

    public function getDetail(): string
    {
        return "{$this->getRecordedAt()} {$this->getDescription()} {$this->getAmount()}{$this->getCurrency()}";
    }
}

src/Controller/RecordController.php
<?php

namespace App\Controller;

use App\Entity\Record;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class RecordController extends AbstractController
{
    /**
     * @Route("/record", name="record")
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $recordRepository = $this->getDoctrine()->getRepository(Record::class);

        $query = $recordRepository->createQueryBuilder('r')->getQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            50
        );

        return $this->render('record/index.html.twig', [
            'controller_name' => 'RecordController',
            'pagination'      => $pagination
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </body>
</html>

templates/record/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>{{ knp_pagination_sortable(pagination, 'Id', 'r.id') }}</th>
            <th{% if pagination.isSorted('a.DateTime') %} class="sorted"{% endif %}>
                {{ knp_pagination_sortable(pagination, 'RecordedAt', 'r.DateTime') }}
            </th>
            <th>{{ knp_pagination_sortable(pagination, 'Amount', ['r.Amount', 'r.DateTime']) }}</th>
        </tr>
        </thead>

        {% for record in pagination %}
            <tr {% if loop.index is odd %}class="color"{% endif %}>
                <td>{{ record.id }}</td>
                <td>{{ record.recordedAt }}</td>
                <td>{{ record.amount }}</td>
            </tr>
        {% endfor %}
    </table>

    <div class="navigation">
    {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}